%% setDipole
% sets the dipole transition moment for an harmonic oscillatr
%% Syntax
% setDipole(u)
%% Description
% setDipole(u) sets the dipole of the harmonic oscillator to u.
%% Detailed Description and Examples
% The dipole set via this method must be understood as a measure for how strong the modelled entity (a cavity for example) reacts to the 
% external light. The time dependent Hamiltonian that is generated by an external field that interacts with a harmonic oscillator is given by
% 
% $$H_e(t) = E(t) \mu \cdot(\sigma^- + \sigma^+)$$
%
% where $\sigma^-$ and $\sigma^+$ denote the lowering and raising operators.