%% traceOut
% trace out a subsystem
%% Syntax 
% * traceOut(name)
%% Description
% traceOut(name) traces out the subsystem _name_. The resulting reduced density matrices
% are safed in the variable _reduced_rho_hist_. Further operations can be performed on these 
% matrices manually and the getConcurrence method relies on them. Mathematically the reduced density matrix is 
% generated by
%
% $$ \rho_r =  \sum_i <n_i |\rho| n_i> $$
%
% where n_i are the kronecker expanded basis vectors of subsystem _name_. 